
image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: npm start

# Ports to expose on workspace startup (optional)
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - eg2.vscode-npm-script
    - vscode.npm
